<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<OutputType>Exe</OutputType>
		<IsAotCompatible>true</IsAotCompatible>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="TUnit" Version="1.17.11" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Roslynator.Analyzers" Version="4.15.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<ProjectReference Include="..\AssemblySharp\AssemblySharp.csproj" />
	</ItemGroup>
</Project>
